### ISSUE TITLE
PATH issue with Shell executor

### ISSUE THREAD

**Issue by imiric** [ayufan/gitlab-ci-multi-runner#1]
Hi!

First of all, thanks for your work on this runner. The multiple tokens per runner is really handy.

I tried it with the Shell executor, but I'm getting the following error with a job that only runs `tox`:

```
Using Shell executor...
Starting shell command...
Running <...>...
Clonning repository...
Cloning into 'runner-7dd2f292-project-2-concurrent-0'...
Checkouting 339e5992 as master...
Reset branch 'master'
HEAD is now at 339e599

tox
Traceback (most recent call last):
  File "/bin/tox", line 9, in <module>
    load_entry_point('tox==1.8.1', 'console_scripts', 'tox')()
  File "/usr/lib/python2.7/site-packages/tox/_cmdline.py", line 25, in main
    config = parseconfig(args, 'tox')
  File "/usr/lib/python2.7/site-packages/tox/_config.py", line 42, in parseconfig
    parseini(config, inipath)
  File "/usr/lib/python2.7/site-packages/tox/_config.py", line 296, in __init__
    self._makeenvconfig(name, section, reader._subs, config)
  File "/usr/lib/python2.7/site-packages/tox/_config.py", line 329, in _makeenvconfig
    vc._basepython_info = config.interpreters.get_info(vc.basepython)
  File "/usr/lib/python2.7/site-packages/tox/interpreters.py", line 29, in get_info
    executable = self.get_executable(name)
  File "/usr/lib/python2.7/site-packages/tox/interpreters.py", line 20, in get_executable
    self.name2executable[name] = e = find_executable(name)
  File "/usr/lib/python2.7/site-packages/tox/interpreters.py", line 121, in find_executable
    return py.path.local.sysfind(name)
  File "/usr/lib/python2.7/site-packages/py/_path/local.py", line 723, in sysfind
    paths = py.std.os.environ['PATH'].split(':')
  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PATH'
kill -s INT 0
Build took 478.057369ms

Build failed with exit status 1
```

It seems that the PATH env var is not getting passed to the child process. I'm not familiar with Go, otherwise I'd try to fix this myself.

This job/build works fine with the official runner, it's just an issue with yours.

Thanks for your help!

Ivan

**Comment by imiric** [comment]
Sorry, I didn't notice I could set the env vars in `config.toml`! Sorry, I'll close this.

**Comment by ayufan** [comment]
Do you have that envs in your PATH? It should be inherited.

**Comment by imiric** [comment]
Yeah, I do, that's what I assumed would happen. Anyway, not an issue since I redefined PATH in `config.toml.`. Thanks!

**Comment by ayufan** [comment]
I'll look into it. What do you think about this project? It was hard to configure? Do you have any thoughts what can be done better?

**Comment by imiric** [comment]
Nah, it was pretty straightforward, I just didn't read all the instructions thoroughly. I'm mainly using it for running multiple jobs/tokens per runner, and it works great so far (can't understand why the official one doesn't have this feature). I'm running shell jobs only so far, so can't comment on the Docker integration, but that's handy to have.

Anyway, good job! Wish I could contribute code, but Go's not my forté. Cheers!

**Comment by ayufan** [comment]
Ok, thanks.
