### ISSUE TITLE
Testing of .deb package

### ISSUE THREAD

**Issue by ayufan** [ayufan/gitlab-ci-multi-runner#12]
Hey guys,

Would you have some time to test these shiny and new deb packages:
https://github.com/ayufan/gitlab-ci-multi-runner#install-and-initial-configuration-for-debian-and-ubuntu

I'm currently preparing upstart version (ubuntu still works on sysv) and systemd version (for centos).

Thanks

/cc @Flink @Bugagazavr @Razer6

**Comment by Razer6** [comment]
Cool. I'll test one tomorrow :) This package works on debian as well as Ubuntu - right?

**Comment by ayufan** [comment]
Yes. I have working one with upstart already. I'm preparing now one for CentOS. It's really, really simple and small.

**Comment by Wolfium** [comment]
I did some small stating tests on CentOS, and got it running manually and I
am not a Unix expert.
That would be really great!

Thanks in advance for you effort...

Regards

**Comment by Bugagazavr** [comment]
so, looks good, successful installed, and works fine on ubuntu 14.04

**Comment by ayufan** [comment]
There's still one thing missing. Upon service shutdown the runner should fail all currently running jobs and send result to the coordinator.

**Comment by Flink** [comment]
Just tried on a debian/wheezy server, it seems to work nice :)
The /etc/default/gitlab-ci-multi-runner file should contain a variable to set the automatic start as a daemon though.

**Comment by ayufan** [comment]
I did test CentOS 7 it works ok too :)

**Comment by ayufan** [comment]
@Flink I guess that update-rc.d is for that

**Comment by Flink** [comment]
@ayufan yeah I think you’re right, programs that define a variable to start as daemon don’t seem to be that common. Sorry! ;)

**Comment by ayufan** [comment]
This are just my thought :)

**Comment by Flink** [comment]
Since you’re logging in /var/log, I think a conf file for logrotate should be included. Something like that maybe:
```
/var/log/gitlab-ci-multi-runner.log {
    weekly
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    copytruncate
}
```

**Comment by ayufan** [comment]
Yeah. I finally managed to add package generation and upload to CI. However I'm not happy with packagecloud.io so this will definitely change. They have pretty bad free plan: 25 packages (currently runner takes 12) and it's impossible to automatically remove older ones.

If you could test once again. There are packages for: debian/wheezy/jessie, ubuntu/precise/trusty/utopic and centos/7.

**Comment by Flink** [comment]
Update well received :)

**Comment by ayufan** [comment]
Thanks :)

**Comment by ayufan** [comment]
So. The only not supported system for now is Centos/6, but it can be done quite easily.

**Comment by ayufan** [comment]
0.1.12 is up with a lot of new features :)

**Comment by Flink** [comment]
Update well received, thanks! :)

**Comment by ayufan** [comment]
Ok. All RedHat based distributions are supported.
