### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ayufan** [ayufan/gitlab-ci-multi-runner#14]
Anyone interested in Windows support?

**Comment by ayufan** [comment]
I could think of creating `cmd` or `PowerShell` compatible build scripts instead of currently used `bash`.

**Comment by sjk07** [comment]
Windows support would be awesome. I have working on getting gitlab-ci working with msbuild for most of the day. Creating a service out of gitlab-ci-runner, modifying the Registry, etc, etc....

**Comment by ayufan** [comment]
It's possible and quite possible to service, but before I do such integration I want to hear from GitLab guys.

**Comment by sjk07** [comment]
Sure, if you need any info about what goes into it, i just went thought the whole process on a windows 2012 server, at least using [gitlab-ci-runner-win](https://github.com/virtualmarc/gitlab-ci-runner-win). I guess the holy grail here would be making the runner as a service and being able to install it via [Chocolatey](https://chocolatey.org/). Hope the GitLab guys think this is a good idea :beer:

**Comment by ayufan** [comment]
I added abstraction over shell scripts. It allows to add support for windows cmd or powershell

**Comment by ayufan** [comment]
Support for Windows is there (on master only for now). Scripts can be run in PowerShell or Windows Batch context. Still you have to install run everything manually.

**Comment by ayufan** [comment]
Anyone interested in trying the latest Windows version? With support for Batch, PowerShell and installation as service?

**Comment by sjk07** [comment]
Ill give it a test sometime on monday

**Comment by sjk07** [comment]
sorry, iv been MIA. 

I tried to get this to build from source but iv never used go before. Any instruction would be much appriciated

**Comment by ayufan** [comment]
@sjk07 Can you follow this instruction and upgrade if possible: https://github.com/ayufan/gitlab-ci-multi-runner/blob/develop/docs/install-on-windows.md ?

**Comment by ayufan** [comment]
@sjk07 Did you manage to test it?

**Comment by sjk07** [comment]
I followed the instructions here: https://github.com/ayufan/gitlab-ci-multi-runner/blob/develop/docs/install-on-windows.md. I'm a little unsure about dependencies here. In setup it says to select docker as the executor and then ruby 2.1 as the image. Are these really required for the windows install? 

I setup the runner and it did register with gitlab-ci. but when trying to start the service, i get a log-in failure exception. Im pretty sure i typed the password in correctly but now i don't know if i can change it anywhere.

Currently testing install on Windows 2012 R2 Server. With x64 multi-runner binary.

**Comment by ayufan** [comment]
@sjk07 It's fixed in 0.1.15 - it will work fine now. If you want to inspect service manually please go to Administrative Tools -> Computer Management -> Services.
