### ISSUE TITLE
Registering runner... forbidden

### ISSUE THREAD

**Issue by axilleas** [ayufan/gitlab-ci-multi-runner#2]
Hey, thanks for this project! I followed the readme to the letter and after the description input I get this:

```
Please enter the gitlab-ci coordinator URL (e.g. http://gitlab-ci.org:3000/ )
https://ci.gitlab.org/
Please enter the gitlab-ci token for this runner
f5a031fc8e067f381d189c76ae70ec7f
Please enter the gitlab-ci description for this runner
GCE
ERRO[0016] 7c1e4992 Registering runner... forbidden     
FATA[0016] Failed to register this runner. Perhaps your SSH key is invalid or you are having network problems 
```

The machine I'm running the runner doesn't have direct internet access and I'm forwarding all the traffic to another machine which is connected to the internet.

Do you have any tips on how could I resolve this? Thanks!

**Comment by ayufan** [comment]
You have to have access to have normal access to ci.gitlab.org.

**Comment by axilleas** [comment]
Lool, nevermind, I just realized what you wrote before you write it...
