### ISSUE TITLE
mysql, php

### ISSUE THREAD

**Issue by huglester** [ayufan/gitlab-ci-multi-runner#22]
Hello,

what would be best approach to add php together with mysql server support?
There would be more packages we would need for building php projects, but those two would be
as an example :)

Thank you for nice unofficial tool :)

**Comment by ayufan** [comment]
I guess to use Docker and select as base image one of these images https://registry.hub.docker.com/u/library/php/ (php:latest?) and select the version you require. For package manager you will probably use composer.json so it should be fine to install all deps every time.

**Comment by ayufan** [comment]
Basically runner registration will be something like that:
```bash
$ gitlab-ci-multi-runner setup \
  --non-interactive \
  --url "https://ci.gitlab.com/" \
  --registration-token "REGISTRATION_TOKEN" \
  --description "latest php with mysql" \
  --executor "docker" \
  --docker-image php:latest --docker-mysql latest
```

**Comment by ayufan** [comment]
Pretty simple :)

**Comment by huglester** [comment]
I am now investigation docker (my 1st time.)

But I don't find in your docs, what are these:
--docker-image php:latest
--docker-mysql latest

php:latest - this one lookslike  image from docker hub.
but when what is --docker-mysql and the `latest` part?

Thanks!

**Comment by ayufan** [comment]
--docker-image is the base image used to execute tests:
in your case it is: https://registry.hub.docker.com/u/library/php/

--docker-mysql is service image which is execute along the base image and
linked to the base one, in your case it is:
https://registry.hub.docker.com/u/library/mysql/

latest stands for version of mysql image, on that page you can find more
versions, ex.: 5.5, 5.6, 5.7.

Kamil


On Fri, Apr 10, 2015 at 3:35 PM, huglester <notifications@github.com> wrote:

> I am now investigation docker (my 1st time.)
>
> But I don't find in your docs, what are these:
> --docker-image php:latest
> --docker-mysql latest
>
> php:latest - this one lookslike image from docker hub.
> but when what is --docker-mysql and the latest part?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayufan/gitlab-ci-multi-runner/issues/22#issuecomment-91559557>
> .
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu
