### ISSUE TITLE
Executor docker - service mysql

### ISSUE THREAD

**Issue by huglester** [ayufan/gitlab-ci-multi-runner#24]
Hello,

first of all, this is something amazing. Thanks for this tool. It just works :)
I have already set up the docker image, which has support for php, composer, phpcs, git, phplint

Now is the mysql part, I am not sure I am going the correct way, during setup, I've chosen I want mysql 5.5.

I see the container starts in the logs, and 'attaches' mysql: (Starting service mysql:5.5 ..) :
```bash
Using Docker executor with image webapp ...
Starting service mysql:5.5 ...
Waiting for services to be up and running...
Running on runner-c2cbe862-project-2-concurrent-0 via huglester-desktop...
Clonning repository...
Cloning into 'runner-c2cbe862-project-2-concurrent-0'...
Checkouting 9a9b3d0d as master...
Reset branch 'master'

mysql -uroot -e "drop database if exists emtctools_test_app;"
bash: line 20: mysql: command not found
kill -s INT 0
```

but the problem is here, I am not sure how this part works?
How this 'step' for mysql works?

Should it attach it somehow 'itself'? 

My config.toml look like this:
```php
concurrent = 1

[[runners]]
  name = "huglester-office"
  url = "https://ci.???.lt/"
  token = "XXX"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  environment = ["MYSQL_ALLOW_EMPTY_PASSWORD=1"]
  shell = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "php55"
    privileged = false
    disable_cache = false
    disable_pull = false
    volumes = ["/cache"]
    cache_dir = ""
    registry = ""
    services = ["mysql:5.5"]
```

But what should be done now? Thanks for any ideas.

**Comment by ayufan** [comment]
There's most probably no mysql command line tool installed. Either connect to database using PHP or install: `apt-get install mysql-client-core`. To connect to database you have to use host: `mysql` - it's hostname linked to separate container.

**Comment by huglester** [comment]
Hello,

thank for reply, after playing for serveral hours, I think I have achieved wanted result (to solve this I installed mysql-client). And thanks for 'host mysql`, I did not find it somehow :)

To sum up, there are few thing which needs to be considered when building PHP apps.
You would probably need to copy over auth.json (part of composer, it contains passwords/tokens) to authentificate with github/bitbucket/gitlab.

I also copy over the id_rsa key, so it can communicate with my GitLab install

I also added this to Dockerfile:
```bash
# Create known_hosts
RUN touch /root/.ssh/known_hosts
# Add bitbuckets key
RUN ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN ssh-keyscan git.????.lt >> /root/.ssh/known_hosts
```

And to speed up the composer, I have added this to config.toml:
    volumes = ["/root/composer/cache"]
it will cache the downloaded packages. 

composer part in Dockerfile:
```bash
# Set environmental variables
ENV COMPOSER_HOME   /root/composer

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN chmod +x        /usr/local/bin/composer
```

That would be probably all.

Thanks once again.
