### ISSUE TITLE
Quotes in systemd unit cause it to fail

### ISSUE THREAD

**Issue by jdmarble** [ayufan/gitlab-ci-multi-runner#25]
After installing the service onto a fresh install of CentOS 7, the service fails to start with the following error:

    Apr 10 17:03:47 localhost systemd[1]: [/etc/systemd/system/gitlab-ci-multi-runner.service:4] Path in condition not absolute, ignoring: "/usr/bin/gitlab-ci-multi-runner"
    Apr 10 17:03:47 localhost systemd[1]: [/etc/systemd/system/gitlab-ci-multi-runner.service:9] Executable path is not absolute, ignoring: "/usr/bin/gitlab-ci-multi-runner" "run" "--working-directory" "/home/gitlab_ci_multi_runner" "--config" "config.toml"
    Apr 10 17:03:47 localhost systemd[1]: gitlab-ci-multi-runner.service lacks ExecStart setting. Refusing.

Removing the quotes from the `ExecStart` setting in the unit file fixes the problem.

**Comment by ayufan** [comment]
It's fixed in 0.1.16 which is already live. Please install latest package.
