### ISSUE TITLE
Runner delete endpoint

### ISSUE THREAD

**Issue by dosire** [ayufan/gitlab-ci-multi-runner#26]
Hi @ayufan can you consider adding a delete function to the runner?

This would call https://gitlab.com/gitlab-org/gitlab-ci/commit/26d6bff9a52ac08df0398495702e149004ba69e4 and allow the runner to delete itself.

This is great for single use runners. Maybe it would be nice to have a script that does: setup, start, stop, delete.

**Comment by ayufan** [comment]
Sure. Functionality is already implemented (https://github.com/ayufan/gitlab-ci-multi-runner/blob/develop/common/network.go#L181) and used for recovering canceled setup.

At first I thought about adding: `verify` command which would test all endpoints and remove the broken one, but there is no API to test such thing.

The `delete` will have to accept `url` and `token` and maybe, but maybe look the config file and remove the deleted entries.

**Comment by dosire** [comment]
@ayufan Nice that it is already implemented. Is the delete function also documented?

**Comment by ayufan** [comment]
It's implemented internally and used internally, not yet exposed as command line.

**Comment by dosire** [comment]
@ayufan That would allow people to make single use runners, so please consider it.

**Comment by ayufan** [comment]
Yes. I'll add that. Did you used `run-single` already?

**Comment by dosire** [comment]
No, does run-single delete the runner at the end of the run?

**Comment by ayufan** [comment]
Nope. `run-single` allows you to pass `url` and `token` and run just one single runner.

**Comment by dosire** [comment]
@ayufan With single user runners I mean runners that just run a single build and afterwards delete themselves from GitLab CI (and exit their docker container process).

**Comment by ayufan** [comment]
I see the reason for having `delete` function, but can you describe use case in single runner mode? You run runner in docker: it register itself for sake of executing one job and later deletes himself?

**Comment by dosire** [comment]
@ayufan Exactly, you can instruct Mesos or Kubernetes to always keep 5 of these runners around. When they did the run they will self-destruct and be replaced.

**Comment by ayufan** [comment]
Ok. Maybe the `run-single` should have also option: `--register` that will automatically `register` (with provided token), `build` and `self-destruct` when finished?

**Comment by ayufan** [comment]
Please take a look at: https://github.com/ayufan/gitlab-ci-multi-runner/blob/develop/commands/delete.go#L50

It's not yet released.

**Comment by dosire** [comment]
@ayufan The run-single with the --register command is a great idea. Or call it run-once

**Comment by dosire** [comment]
@ayufan Regarding the preview of delete.go you linked, can't the runner get this data from its config file? Or is that what the code says.

**Comment by ayufan** [comment]
The config file can contain multiple runners. Which one to choose?

**Comment by dosire** [comment]
@ayufan Ah, if it is hard to indicate which of the runners you want to delete I can live with the solution as you proposed it.

**Comment by ayufan** [comment]
It got me to thinking why do you prefer to share `registration` token instead of sharing `registered` runner token?

**Comment by dosire** [comment]
@ayufan I don't understand, where do I say that and what is the difference? I think there are only registrations and runner tokens.

**Comment by ayufan** [comment]
@dosire You said about deleting runner from the coordinator after executing job, but my question is how in the first place you receive the runner token - you need to have registration or project token for that. Can you clarify how will it work?

**Comment by dosire** [comment]
I imagine that a platform such as Mesos or Kubernetes starts a container that executes `run-once --registration-token XXXXX`. Each runner will:

1. Register itself and get a runner token
2. Poll for jobs
3. Execute a job (clone, test, etc.)
4. Delete itself from GitLab CI
5. Exit its process

After the process is exited the platform will terminate the runner container. And because the number of active runner containers has dropped under a limit (for example: there must be 10 active shared runners) it will start a new one.

**Comment by dosire** [comment]
An example of a setup that is kinda like this can be found on https://github.com/deric/gitlab-ci-mesos

**Comment by ayufan** [comment]
I understand that, but I'm also thinking isn't it better to just share `config` with runner's token and all configuration, and execute as many workers as needs with that config?

It will not create a new runner for each container, but it will still run jobs with already configured runner, which may have tags and other specific things assigned.

**Comment by dosire** [comment]
@ayufan I think in GitLab CI one runner can run only one job at a time. /cc @randx

**Comment by ayufan** [comment]
There's no such restriction. This how concurrency works now. You can ask
for runner's jobs as long as you can process them.

On Thursday, April 23, 2015, Sytse Sijbrandij <notifications@github.com>
wrote:

> @ayufan <https://github.com/ayufan> I think in GitLab CI one runner can
> run only one job at a time. /cc @randx <https://github.com/randx>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayufan/gitlab-ci-multi-runner/issues/26#issuecomment-95368432>
> .
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by randx** [comment]
@dosire I think @ayufan is right. Coordinator does not care how many jobs runner have at exact moment.

**Comment by randx** [comment]
But I am wondering how `gitlab-ci-multi-runner` determine how many jobs it can process at exact moment? Is it a configurable value or based on hardware?

**Comment by Bugagazavr** [comment]
@randx `limit` value in runner config, by default limit equal to zero ( only one job can be executed at moment )

**Comment by ayufan** [comment]
@Bugagazavr Almost true.

There are two settings:
* `concurrent` (global value) - limits number of concurrent jobs globally for all registered runners
* `runner.limit` (runner value) - limits number of jobs that can be run concurrently by specific runner, 0 - means no limit. Use case: you have test runner and deploy runner, and basically is not good to have deploy runner work in concurrent mode, so you limit it to 1.

@randx during setup `concurrent` is set to `1`, but I think now that maybe best possible default should be used `number of CPU cores`. So basically runner would be default run as many jobs concurrently as number of cores.

Does it make sense?

**Comment by randx** [comment]
>  but I think now that maybe best possible default should be used number of CPU cores

@ayufan it depends on what you test. For example in GitLab we need 2GB to test one build. So for 4 cores 2GB box we cant have `concurrent ` 4. It would be 1 instead. But for libraries it makes sense

**Comment by ayufan** [comment]
Ok. I'll make such change. It can be easily limited. I'll also later add: ```gitlab-ci-multi-runner config``` that it will make it easy to edit.

**Comment by dosire** [comment]
FYI I changed to docs to reflect one runner can run multiple jobs at the same time. https://gitlab.com/gitlab-com/www-gitlab-com/commit/e7593c1ad6ba8a7d3d317c1cba72503167f41779

**Comment by dosire** [comment]
@ayufan I now finally understand the concept of multiple runners using the same registration token. Maybe using the word delete is confusing, since it seems to be about runners. Maybe add an option 'deregister' that deletes all the runners and deregisters the registration token.

**Comment by ayufan** [comment]
Sure I will change it. Maybe I should change the `setup` too? It makes more sense to name it `register` and `unregister` :)

**Comment by dosire** [comment]
@ayufan I think changing it into register and unregister makes sense.

**Comment by ayufan** [comment]
Thanks for input. I'll make such change :)

**Comment by dosire** [comment]
@ayufan Thanks!

**Comment by ayufan** [comment]
Closing that in favor of https://gitlab.com/gitlab-org/gitlab-ci-multi-runner
