### ISSUE TITLE
register two runners?

### ISSUE THREAD

**Issue by huglester** [ayufan/gitlab-ci-multi-runner#27]
Hello, 

if I understand correct, it should be possible to register two or more runners? 
Why I want it, is that, for example, I could see 3 different runners in Gitlab CI, so every runner has it's own tag, so this runner could be bound to the specific projects.

config is like this: 
```
concurrent = 1

[[runners]]
  name = "php56"
  url = "https://ci.???.lt/"
  token = "????"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  environment = ["MYSQL_ALLOW_EMPTY_PASSWORD=1"]
  shell = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "php56"
    privileged = false
    disable_cache = false
    disable_pull = false
    volumes = ["/cache", "/root/composer/cache"]
    cache_dir = ""
    registry = ""
    services = ["mysql:5.5"]

[[runners]]
  name = "docker-builder"
  url = "https://ci.???.lt/"
  token = "???"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  shell = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "docker-build-tester"
    privileged = false
    disable_cache = false
    disable_pull = false
    cache_dir = ""
    registry = ""
    services = []
```

so I registered two runners using this config? to the same Gitlab CI.. is it a correct way? 
I see the gitlab-multi-runner daemon is running, but the 2nd runner did not register in Gitlab CI.

Thank you

**Comment by ayufan** [comment]
Just execute: `gitlab-ci-multi-runner setup` multiple times. And don't forget to change `concurrent` parameter in `config.toml`.

**Comment by huglester** [comment]
Sorry for not replying. Yes it works!
