### ISSUE TITLE
Broken links for Windows download

### ISSUE THREAD

**Issue by Ridermansb** [ayufan/gitlab-ci-multi-runner#29]
Links for download [x86](https://repo.ayufan.eu/gitlab-ci-multi-runner/latest/binaries/gitlab-ci-multi-runner-windows-386.exe) and [amd64](https://repo.ayufan.eu/gitlab-ci-multi-runner/latest/binaries/gitlab-ci-multi-runner-windows-amd64.exe) are broken.

Both in [install-on-windows.md](https://github.com/ayufan/gitlab-ci-multi-runner/blob/master/docs/install-on-windows.md)

**Comment by ayufan** [comment]
Fixed. Please try again :)

**Comment by Ridermansb** [comment]
Ok, tks.

Another problem, my chrome say thats is a bad link

![image](https://cloud.githubusercontent.com/assets/725337/7333359/30ccfaf2-eb43-11e4-9d58-c761829c5628.png)
