### ISSUE TITLE
Certificate verification fails

### ISSUE THREAD

**Issue by Razer6** [ayufan/gitlab-ci-multi-runner#3]
I'm using 2 runners on different servers to build the same project. One of fails while verifying the CAfile:

```
error: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none while accessing https://gitlab-ci-token:xxxxxx@<gitlab-server>/<group>/<project>.git/info/refs
```

**Comment by ayufan** [comment]
Using docker or shell?

**Comment by ayufan** [comment]
If shell try to see what will show `curl --head https://<gitlab-server>`.

For me it looks like a problem with self-signed certificate or not full certificate path.

**Comment by Razer6** [comment]
It's a chained certificate. I already checked the chai - it's valid. It seems my server (where I don't have root access) does not trust my CA :(

Is git bundled to the binary? I tried disabling ssl verification of git but this does not have an effect to the runner.

**Comment by ayufan** [comment]
Nope. It uses installed binaries. 

You can add env to `config.toml` that will disable certificate check:
```[[runners]]
environment=["GIT_SSL_NO_VERIFY=1"]
```

You need to add environment to each runner.

**Comment by Razer6** [comment]
Thanks. That works!

**Comment by ayufan** [comment]
BTW. How do you like it?

**Comment by Razer6** [comment]
I really like it. I'm using it on OSX (with root access) and on linux (without root). The biggest issue I had in the past was the required root access. My used server has a rather old ruby. Installing the official runner without root was a pain. Having this binary makes this pretty easy :+1:

**Comment by ayufan** [comment]
Great to hear :)
