### ISSUE TITLE
Retried build fail because index.lock exists

### ISSUE THREAD

**Issue by Razer6** [ayufan/gitlab-ci-multi-runner#4]
If I retry a job I get the following error message. If I delete the build directory, I successfully can rebuild the project.

```
Using Shell executor...
Starting shell command...
Running servitus...
Fetching changes...
fatal: Unable to create '/MY-HOME/tmp/builds/runner-a48b51d2-project-10-concurrent-0/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Build took 491.283239ms

Build failed with exit status 128
```

**Comment by ayufan** [comment]
Does it happen on osx or linux?

**Comment by Razer6** [comment]
> Does it happen on osx or linux? 
Happend on linux.

> Did you canceled the build?
No, it was a retried built (after failed)

>  Can you also check when it happens are there git process running?
I'll check

**Comment by Razer6** [comment]
I tried to reproduce this issue. No chance today. Closing this for now. :)

**Comment by ayufan** [comment]
Thanks.
