### ISSUE TITLE
Rubygems caching with docker

### ISSUE THREAD

**Issue by Bugagazavr** [ayufan/gitlab-ci-multi-runner#6]
Any examples how i can cache rubygems for specific job?

**Comment by ayufan** [comment]
Check this: https://github.com/ayufan/gitlab-ci-multi-runner#how-to-configure-runner-for-gitlab-ci-integration-tests

By default `/cache` folder is added and you can `bundle install` into `cache`.

**Comment by Bugagazavr** [comment]
@ayufan thanks, looks like i need to register second worker if i want to get matrix builds?

**Comment by ayufan** [comment]
Nope. Just up limits. The same worker will process multiple jobs, each will be in separate container with separate caches.

**Comment by ayufan** [comment]
Look at `concurrent` in global section and `limit` in runner's section.

**Comment by Bugagazavr** [comment]
Great, thanks, this is works for me
