### ISSUE TITLE
Bundle not working

### ISSUE THREAD

**Issue by Flink** [ayufan/gitlab-ci-multi-runner#8]
Hi!

Just trying your project which seems really cool but I’ve a big problem. When executing `bundle install` in the container, it doesn’t work and all I have is this error: `/builds/runner-3954deff-project-3-concurrent-0 not found`. Trying with `bundle install --deployment` says my Gemfile.lock is not present but it is. I really don’t understand what’s the matter here (all paths seem ok, ls, pwd, etc show that the files are where they should be).

Thanks!

**Comment by Flink** [comment]
Ok found it! The `BUNDLE_GEMFILE` was set to nothing (instead of not being set I think) so bundler was unable to find its Gemfile. Setting it to `$PWD/Gemfile` or unset it will work. But I think it still a bug ;)

**Comment by ayufan** [comment]
It's strange and it should happen.

This is one of the examples of ruby applications in docker container working for me: https://github.com/ayufan/gitlab-ci-multi-runner#how-to-configure-runner-for-gitlab-ci-integration-tests

Maybe you have some specific setup?

Did you use v0.1.8 or different one?

**Comment by Flink** [comment]
I just tried you project so yes I have the latest version (0.1.8) but I’m using an image with ruby 2.2 (ruby:2.2) and only postgresql (9.3) in it.
I’m not doing any particular setup in my gitlab ci job:
```shell
unset BUNDLE_GEMFILE
bundle install --deployment --path /cache -j8
cp config/database.yml.example config/database.yml
bundle exec rake db:setup RAILS_ENV=test
bundle exec rspec spec --format progress
```

**Comment by ayufan** [comment]
So: unset BUNDLE_GEMFILE did fix it for you?

**Comment by Flink** [comment]
Yep!

**Comment by ayufan** [comment]
Does it happen on docker right? So I could easily test it. You are testing gitlab-ci?

**Comment by Flink** [comment]
yes it’s inside a docker container :)
This is my conf if it can help:
```
$ cat config.toml 
concurrent = 1
root_dir = ""

[[runners]]
  name = "ruby-2.2"
  url = "CI"
  token = "TOKEN"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  shell_script = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "ruby:2.2"
    privileged = false
    disable_cache = false
    disable_pull = false
    volumes = ["/cache"]
    cache_dir = ""
    registry = ""
    services = ["postgres:9.3"]
```
I’m using GitLab-CI for my projects since some time now but previously I had a runner setup with rbenv. It doesn’t always play nice with different versions of ruby and your solution seems really great :)

**Comment by ayufan** [comment]
Great to hear :)

**Comment by ayufan** [comment]
Ok. I see that it doesn't work: https://ci.gitlab.com/projects/42/builds/10030. However it doesn't happen on ruby:2.1 :)

**Comment by Flink** [comment]
Oh ok so it’s specific to ruby 2.2, good to know! ;)

**Comment by ayufan** [comment]
Or maybe it's my problem: https://github.com/ayufan/gitlab-ci-multi-runner/commit/0756b640f2bce3640d40265d36ca9cd36758ec80

**Comment by ayufan** [comment]
I just pushed the 0.1.9 it should get released within a couple of minutes.

**Comment by Flink** [comment]
Great! :+1:
